pipeline {
    agent any

    stages {
        stage('Check compiler') {
            steps {
                sh 'g++ --version'
            }
        }

        stage('Build') {
            steps {
                sh 'g++ -std=c++20 HelloWorld/HelloWorld.cpp -o HelloWorldApp'
            }
        }

        stage('Run') {
            steps {
                sh './HelloWorldApp'
            }
        }
            
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'HelloWorldApp', fingerprint: true
            }
        }
    }
}
