pipeline {
    agent any

    stages {
        stage('Install compiler') {
            steps {
                sh 'which g++ || sudo apt update && sudo apt install -y g++'
            }
        }

        stage('Build') {
            steps {
                sh 'g++ -std=c++20 HelloWorld/HelloWorld.cpp -o HelloWorldApp'
            }
        }

        stage('Run') {
            steps {
                sh './HelloWorldApp'
            }
        }
    }
}